Repository SOPT-all/35-APPJAM-ANDROID-BBANGZIP, pull requests merged in 2025-01, with the labels that each got.

#6 [init] Theme 기초 세팅
  app/src/main/java/org/android/bbangzip/ui/theme/BbangZipTheme.kt
  app/src/main/java/org/android/bbangzip/ui/theme/Color.kt
  app/src/main/java/org/android/bbangzip/ui/theme/ColorScheme.kt
  app/src/main/java/org/android/bbangzip/ui/theme/Opacity.kt
  app/src/main/java/org/android/bbangzip/ui/theme/Theme.kt
  app/src/main/java/org/android/bbangzip/ui/theme/Type.kt
  app/src/main/res/font/pretendard_bold.ttf
  app/src/main/res/font/pretendard_medium.ttf
  app/src/main/res/font/pretendard_small.ttf
  gradlew
Labels: 🩷INIT🩷

#8 [Init] Icon 기초 세팅
  app/src/main/res/drawable/ic_announcement_default_24.xml
  app/src/main/res/drawable/ic_bell_default_24.xml
  app/src/main/res/drawable/ic_bell_ringing_default_24.xml
  app/src/main/res/drawable/ic_book_default_24.xml
  app/src/main/res/drawable/ic_bubble_default_24.xml
  app/src/main/res/drawable/ic_calendar_check_default_24.xml
  app/src/main/res/drawable/ic_calendar_default_24.xml
  app/src/main/res/drawable/ic_calendar_plus_default_24.xml
  app/src/main/res/drawable/ic_check_circle_default_24.xml
  app/src/main/res/drawable/ic_check_thick_24.xml
  app/src/main/res/drawable/ic_checkcircle_default_24.xml
  app/src/main/res/drawable/ic_chevrondown_default_24.xml
  app/src/main/res/drawable/ic_chevrondown_small_24.xml
  app/src/main/res/drawable/ic_chevrondown_thick_24.xml
  app/src/main/res/drawable/ic_chevrondown_thick_small_24.xml
  app/src/main/res/drawable/ic_chevronleft_thick_small_24.xml
  app/src/main/res/drawable/ic_chevronleft_tight_thick_small_24.xml
  app/src/main/res/drawable/ic_chevronright_thick_small_24.xml
  app/src/main/res/drawable/ic_chevronright_tight_thick_small_24.xml
  app/src/main/res/drawable/ic_chevronup_default_24.xml
  app/src/main/res/drawable/ic_chevronup_small_24.xml
  app/src/main/res/drawable/ic_chevronup_thick_24.xml
  app/src/main/res/drawable/ic_chevronup_thick_small_24.xml
  app/src/main/res/drawable/ic_circle_default_24.xml
  app/src/main/res/drawable/ic_edit_default_24.xml
  app/src/main/res/drawable/ic_file_check_default_24.xml
  app/src/main/res/drawable/ic_filter_default_24.xml
  app/src/main/res/drawable/ic_info_circle_default_24.xml
  app/src/main/res/drawable/ic_kakao_default_24.xml
  app/src/main/res/drawable/ic_lock_default_28.xml
  app/src/main/res/drawable/ic_menu_kebab_default_24.xml
  app/src/main/res/drawable/ic_messagebox_default_24.xml
  app/src/main/res/drawable/ic_messagebox_noti_default_24.xml
  app/src/main/res/drawable/ic_messagebox_text_square_default_24.xml
  app/src/main/res/drawable/ic_page_check_default_24.xml
  app/src/main/res/drawable/ic_plus_circle_default_24.xml
  app/src/main/res/drawable/ic_plus_default_24.xml
  app/src/main/res/drawable/ic_plus_thick_24.xml
  app/src/main/res/drawable/ic_return_default_24.xml
  app/src/main/res/drawable/ic_search_large_24.xml
  app/src/main/res/drawable/ic_trash_default_24.xml
  app/src/main/res/drawable/ic_trophy_default_24.xml
  app/src/main/res/drawable/ic_user_one_default_24.xml
  app/src/main/res/drawable/ic_user_plus_default_24.xml
  app/src/main/res/drawable/ic_user_two_default_24.xml
  app/src/main/res/drawable/ic_x_circle_default_24.xml
  app/src/main/res/drawable/ic_x_large_24.xml
  app/src/main/res/drawable/ic_x_small_24.xml
Labels: 🩷INIT🩷, 🦁재민🦁

#15 [feat] 공통 컴포넌트 Chip 구현
  app/src/main/java/org/android/bbangzip/presentation/component/chip/BbangZipChip.kt
Labels: ✨FEAT✨, 🐯승범🐯

#10 [feat] Bottom navigation 구현
  app/src/main/java/org/android/bbangzip/presentation/type/BottomNavigationType.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/component/BottomNavigationBar.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/util/modifier/ModifierExt.kt
  app/src/main/res/values/strings.xml
Labels: ✨FEAT✨, 🦁재민🦁

#25 [init] shadow 기초세팅
  app/src/main/java/org/android/bbangzip/presentation/type/BbangZipShadowType.kt
  app/src/main/java/org/android/bbangzip/ui/theme/model/ShadowOption.kt
Labels: ✨FEAT✨, 🐯승범🐯

#23 [feat] Custom SnackBar 제작
  app/src/main/java/org/android/bbangzip/presentation/component/snackbar/BbangZipSnackBar.kt
  app/src/main/java/org/android/bbangzip/presentation/component/snackbar/BbangZipSnackBarHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectScreen.kt
Labels: ✨FEAT✨, 🐯승범🐯

#30 [fix] SubjectCard 컴포넌트 수정
  app/src/main/java/org/android/bbangzip/presentation/component/card/SubjectCard.kt
Labels: 🛠️FIX🛠️, 🐯승범🐯

#22 [feat] Progress Bar 컴포넌트 구현
  app/src/main/java/org/android/bbangzip/presentation/component/card/SubjectCard.kt
  app/src/main/java/org/android/bbangzip/presentation/component/progressbar/BbangZipBasicProgressBar.kt
  app/src/main/java/org/android/bbangzip/presentation/component/progressbar/BbangZipLevelProgressBar.kt
  app/src/main/java/org/android/bbangzip/presentation/component/progressbar/OnboardingProgressBar.kt
  app/src/main/java/org/android/bbangzip/presentation/component/pushicon/BbangZipPushIcon.kt
  app/src/main/java/org/android/bbangzip/presentation/component/pushicon/BbangZipPushIconWithText.kt
  app/src/main/java/org/android/bbangzip/presentation/model/BbangZipPushIconState.kt
  app/src/main/java/org/android/bbangzip/presentation/type/BbangZipLevelType.kt
  app/src/main/java/org/android/bbangzip/presentation/type/OnboardingType.kt
  app/src/main/java/org/android/bbangzip/presentation/type/PushIconType.kt
  app/src/main/res/values/strings.xml
Labels: ✨FEAT✨, 🐬지은🐬

#28 [feat] Balloon 컴포넌트 구현
  app/src/main/java/org/android/bbangzip/presentation/component/balloon/BalloonContainer.kt
  app/src/main/java/org/android/bbangzip/presentation/component/balloon/BottomTailBalloon.kt
  app/src/main/java/org/android/bbangzip/presentation/component/balloon/TopTailBalloon.kt
  app/src/main/java/org/android/bbangzip/presentation/util/modifier/ModifierExt.kt
  app/src/main/res/drawable/ic_balloon_tail_down_8.xml
  app/src/main/res/drawable/ic_balloon_tail_up_8.xml
Labels: ✨FEAT✨, 🐯승범🐯

#19 [Feat] Button 컴포넌트 구현
  app/src/main/java/org/android/bbangzip/presentation/component/button/BbangZipButton.kt
  app/src/main/java/org/android/bbangzip/presentation/component/button/BbangZipButtonSlot.kt
  app/src/main/java/org/android/bbangzip/presentation/type/BbangZipButtonType.kt
  app/src/main/res/values/strings.xml
Labels: ✨FEAT✨, 🦁재민🦁

#14 [feat] TextField 컴포넌트 구현
  app/src/androidTest/java/org/android/bbangzip/ExampleInstrumentedTest.kt
  app/src/main/java/org/android/bbangzip/presentation/component/textfield/BbangZipBasicTextField.kt
  app/src/main/java/org/android/bbangzip/presentation/component/textfield/BbangZipSimpleTextField.kt
  app/src/main/java/org/android/bbangzip/presentation/component/textfield/BbangZipTextFieldSlot.kt
  app/src/main/java/org/android/bbangzip/presentation/model/BbangZipTextFieldInputState.kt
  app/src/main/java/org/android/bbangzip/presentation/type/BbangZipTextFieldType.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/friend/FriendScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/util/modifier/ModifierExt.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/android/bbangzip/ExampleUnitTest.kt
Labels: ✨FEAT✨, 🐬지은🐬

#38 [init] Proto DataStore 구현
  app/build.gradle.kts
  app/src/main/java/org/android/bbangzip/data/datasource/local/UserLocalDataSource.kt
  app/src/main/java/org/android/bbangzip/data/datasource/local/serializer/UserSerializer.kt
  app/src/main/java/org/android/bbangzip/data/repositoryImpl/DummyRepositoryImpl.kt
  app/src/main/java/org/android/bbangzip/data/repositoryImpl/UserRepositoryImpl.kt
  app/src/main/java/org/android/bbangzip/data/util/context/ContextExt.kt
  app/src/main/java/org/android/bbangzip/di/RepositoryModule.kt
  app/src/main/java/org/android/bbangzip/di/UseCaseModule.kt
  app/src/main/java/org/android/bbangzip/domain/repository/local/UserRepository.kt
  app/src/main/java/org/android/bbangzip/domain/repository/remote/DummyRepository.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/FetchDummyUseCase.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/dummy/DummyScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/dummy/DummyViewModel.kt
  app/src/main/proto/user_prefs.proto
  gradle/libs.versions.toml
Labels: 🩷INIT🩷, 🐬지은🐬

#35 [fix] ToDo Card 수정
  app/src/main/java/org/android/bbangzip/presentation/component/card/ToDoCard.kt
Labels: 🛠️FIX🛠️, 🐯승범🐯

#32 [feat] component picker 구현
  app/src/main/java/org/android/bbangzip/presentation/component/wheelpicker/BbangZipDatePicker.kt
  app/src/main/java/org/android/bbangzip/presentation/component/wheelpicker/BbangZipPicker.kt
  app/src/main/java/org/android/bbangzip/presentation/component/wheelpicker/BbangZipSemesterPicker.kt
  app/src/main/java/org/android/bbangzip/presentation/model/Date.kt
  app/src/main/java/org/android/bbangzip/presentation/model/Semester.kt
  app/src/main/java/org/android/bbangzip/presentation/type/SemesterType.kt
  app/src/main/java/org/android/bbangzip/presentation/util/constant/DateConstants.kt
  app/src/main/java/org/android/bbangzip/presentation/util/graphic/GraphicExt.kt
  app/src/main/java/org/android/bbangzip/presentation/util/modifier/ModifierExt.kt
Labels: ✨FEAT✨, 🦁재민🦁

#37 [feat] Top Bar 컴포넌트 구현
  app/src/main/java/org/android/bbangzip/presentation/component/topbar/BbangZipMenuTopBar.kt
Labels: ✨FEAT✨, 🦁재민🦁

#42 [feat] Splash/Login UI 구현
  app/build.gradle.kts
  app/src/main/java/org/android/bbangzip/presentation/ui/login/LoginContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/login/LoginNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/login/LoginRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/login/LoginScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainActivity.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/splash/SplashScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectNavigation.kt
  app/src/main/res/drawable/ic_background_circle_accent.xml
  app/src/main/res/drawable/img_login1.png
  app/src/main/res/drawable/img_login2.png
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: ✨FEAT✨, 🐬지은🐬

#27 [feat] Bottom Sheet 컴포넌트 구현
  app/src/main/java/org/android/bbangzip/presentation/component/bottomsheet/BbangZipBasicModalBottomSheet.kt
  app/src/main/java/org/android/bbangzip/presentation/component/bottomsheet/BbangZipDatePickerBottomSheet.kt
  app/src/main/java/org/android/bbangzip/presentation/component/bottomsheet/BbangZipListDefaultPickerBottomSheet.kt
  app/src/main/java/org/android/bbangzip/presentation/component/bottomsheet/BbangZipListPickerBottomSheet.kt
  app/src/main/java/org/android/bbangzip/presentation/component/bottomsheet/BbangZipOneButtonBottomSheet.kt
  app/src/main/java/org/android/bbangzip/presentation/component/bottomsheet/BbangZipTwoButtonBottomSheet.kt
  app/src/main/java/org/android/bbangzip/presentation/model/ExamDate.kt
Labels: ✨FEAT✨, 🐬지은🐬

#47 [feat] Onboarding UI 구현
  app/src/main/java/org/android/bbangzip/data/repositoryImpl/UserRepositoryImpl.kt
  app/src/main/java/org/android/bbangzip/domain/repository/local/UserRepository.kt
  app/src/main/java/org/android/bbangzip/presentation/component/progressbar/OnboardingProgressBar.kt
  app/src/main/java/org/android/bbangzip/presentation/component/textfield/BbangZipBasicTextField.kt
  app/src/main/java/org/android/bbangzip/presentation/component/textfield/BbangZipSimpleTextField.kt
  app/src/main/java/org/android/bbangzip/presentation/component/wheelpicker/BbangZipSemesterPicker.kt
  app/src/main/java/org/android/bbangzip/presentation/model/BbangZipTextFieldInputState.kt
  app/src/main/java/org/android/bbangzip/presentation/model/OnboardingInfo.kt
  app/src/main/java/org/android/bbangzip/presentation/type/BbangZipTextFieldType.kt
  app/src/main/java/org/android/bbangzip/presentation/type/OnboardingType.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/friend/FriendScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/OnboardingContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/navigation/OnboardingEndNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/navigation/OnboardingStartNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/onboarding/OnboardingRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/onboarding/OnboardingScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/onboardingend/OnboardingEndRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/onboardingend/OnboardingEndScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/onboardingstart/OnboardingStartRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/onboardingstart/OnboardingStartScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/util/base/BaseViewModel.kt
  app/src/main/proto/user_prefs.proto
  app/src/main/res/drawable/img_onboarding_start.png
  app/src/main/res/values/strings.xml
Labels: ✨FEAT✨, 🐬지은🐬

#45 [feat] 오늘 할 일 뷰 구현
  app/src/main/java/org/android/bbangzip/domain/model/ToDoCardEntity.kt
  app/src/main/java/org/android/bbangzip/domain/model/ToDoInfoEntity.kt
  app/src/main/java/org/android/bbangzip/presentation/component/balloon/BalloonContainer.kt
  app/src/main/java/org/android/bbangzip/presentation/component/bottomsheet/BbangZipBasicModalBottomSheet.kt
  app/src/main/java/org/android/bbangzip/presentation/component/button/BbangZipButton.kt
  app/src/main/java/org/android/bbangzip/presentation/component/card/ToDoCard.kt
  app/src/main/java/org/android/bbangzip/presentation/model/card/ToDoCardModel.kt
  app/src/main/java/org/android/bbangzip/presentation/type/BbangZipButtonType.kt
  app/src/main/java/org/android/bbangzip/presentation/type/BbangZipCardType.kt
  app/src/main/java/org/android/bbangzip/presentation/type/ToDoFilterType.kt
  app/src/main/java/org/android/bbangzip/presentation/type/ToDoScreenType.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/component/BottomNavigationBar.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/navigation/TodoNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/pendingtodoadd/TodoAddPendingContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/pendingtodoadd/TodoAddPendingRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/pendingtodoadd/TodoAddPendingScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/pendingtodoadd/TodoAddPendingViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/pendingtodoadd/navigation/TodoAddPendingNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/todoadd/TodoAddContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/todoadd/TodoAddRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/todoadd/TodoAddScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/todoadd/TodoAddViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/todoadd/navigation/TodoAddNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/util/modifier/ModifierExt.kt
  app/src/main/java/org/android/bbangzip/ui/theme/Type.kt
  app/src/main/res/values/strings.xml
Labels: ✨FEAT✨, 🐯승범🐯

#56 [feat] UserService API 연결
  .github/workflows/bbangzip_ci.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/android/bbangzip/BbangZipApp.kt
  app/src/main/java/org/android/bbangzip/data/datasource/local/serializer/UserSerializer.kt
  app/src/main/java/org/android/bbangzip/data/datasource/remote/UserRemoteDataSource.kt
  app/src/main/java/org/android/bbangzip/data/dto/request/RequestOnboardingDto.kt
  app/src/main/java/org/android/bbangzip/data/dto/response/ResponseReissueDto.kt
  app/src/main/java/org/android/bbangzip/data/dto/response/ResponseUserDto.kt
  app/src/main/java/org/android/bbangzip/data/interceptor/AuthInterceptor.kt
  app/src/main/java/org/android/bbangzip/data/repositoryImpl/local/UserLocalRepositoryImpl.kt
  app/src/main/java/org/android/bbangzip/data/repositoryImpl/remote/DummyRepositoryImpl.kt
  app/src/main/java/org/android/bbangzip/data/repositoryImpl/remote/UserRepositoryImpl.kt
  app/src/main/java/org/android/bbangzip/data/service/KakaoAuthService.kt
  app/src/main/java/org/android/bbangzip/data/service/UserService.kt
  app/src/main/java/org/android/bbangzip/data/util/base/BaseResponse.kt
  app/src/main/java/org/android/bbangzip/data/util/constant/ApiConstants.kt
  app/src/main/java/org/android/bbangzip/di/KakaoModule.kt
  app/src/main/java/org/android/bbangzip/di/RepositoryModule.kt
  app/src/main/java/org/android/bbangzip/di/ServiceModule.kt
  app/src/main/java/org/android/bbangzip/di/UseCaseModule.kt
  app/src/main/java/org/android/bbangzip/domain/model/OnboardingEntity.kt
  app/src/main/java/org/android/bbangzip/domain/model/ReissueEntity.kt
  app/src/main/java/org/android/bbangzip/domain/model/UserEntity.kt
  app/src/main/java/org/android/bbangzip/domain/repository/local/UserLocalRepository.kt
  app/src/main/java/org/android/bbangzip/domain/repository/remote/UserRepository.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/DeleteLogoutUseCase.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/DeleteWithdrawUseCase.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/PostOnboardingUseCase.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/dummy/DummyViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/login/LoginContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/login/LoginRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/login/LoginScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/MyContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/MyNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/MyRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/MyScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/MyViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/OnboardingViewModel.kt
  app/src/main/proto/user_prefs.proto
  settings.gradle.kts
Labels: ✨FEAT✨, 🐬지은🐬

#50 [feat] Piece Service API 구현
  app/src/main/java/org/android/bbangzip/data/datasource/remote/AssignToTodayRemoteDataSource.kt
  app/src/main/java/org/android/bbangzip/data/datasource/remote/DummyRemoteDataSource.kt
  app/src/main/java/org/android/bbangzip/data/datasource/remote/HideRemoteDataSource.kt
  app/src/main/java/org/android/bbangzip/data/datasource/remote/MarkDoneRemoteDataStore.kt
  app/src/main/java/org/android/bbangzip/data/datasource/remote/MarkUnDoneRemoteDataStore.kt
  app/src/main/java/org/android/bbangzip/data/datasource/remote/TodayOrdersRemoteDataSource.kt
  app/src/main/java/org/android/bbangzip/data/datasource/remote/TodoRemoteDataSource.kt
  app/src/main/java/org/android/bbangzip/data/dto/request/RequestMarkDoneDto.kt
  app/src/main/java/org/android/bbangzip/data/dto/request/RequestPieceIdDto.kt
  app/src/main/java/org/android/bbangzip/data/dto/response/ResponseMarkDoneDto.kt
  app/src/main/java/org/android/bbangzip/data/dto/response/ResponseTodayOrdersDto.kt
  app/src/main/java/org/android/bbangzip/data/dto/response/ResponseTodoDto.kt
  app/src/main/java/org/android/bbangzip/data/repositoryImpl/PieceRepositoryImpl.kt
  app/src/main/java/org/android/bbangzip/data/service/DummyService.kt
  app/src/main/java/org/android/bbangzip/data/service/PieceService.kt
  app/src/main/java/org/android/bbangzip/di/RepositoryModule.kt
  app/src/main/java/org/android/bbangzip/di/ServiceModule.kt
  app/src/main/java/org/android/bbangzip/di/UseCaseModule.kt
  app/src/main/java/org/android/bbangzip/domain/model/BadgeCardListEntity.kt
  app/src/main/java/org/android/bbangzip/domain/model/ToDoCardEntity.kt
  app/src/main/java/org/android/bbangzip/domain/model/ToDoInfoEntity.kt
  app/src/main/java/org/android/bbangzip/domain/repository/remote/DummyRepository.kt
  app/src/main/java/org/android/bbangzip/domain/repository/remote/PieceRepository.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/FetchDummyUseCase.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/GetAddTodoListUseCase.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/GetToInfoUseCase.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/PostAddTodoItemListUseCase.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/PostCompleteCardIdUseCase.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/PostDeletedItemListUseCase.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/PostUnCompleteCardIdUseCase.kt
  app/src/main/java/org/android/bbangzip/presentation/component/balloon/BalloonContainer.kt
  app/src/main/java/org/android/bbangzip/presentation/component/bottomsheet/BbangZipGetBadgeBottomSheet.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/dummy/DummyViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/pendingtodoadd/TodoAddPendingContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/pendingtodoadd/TodoAddPendingRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/pendingtodoadd/TodoAddPendingViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/todoadd/TodoAddContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/todoadd/TodoAddRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/todoadd/TodoAddViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/util/constant/ToDoConstants.kt
  app/src/main/res/values/strings.xml
Labels: ✨FEAT✨, 🐯승범🐯

#58 [feat] friend UI 구현
  app/src/main/java/org/android/bbangzip/data/dto/response/ResponseMarkDoneDto.kt
  app/src/main/java/org/android/bbangzip/presentation/component/card/FriendCard.kt
  app/src/main/java/org/android/bbangzip/presentation/model/card/FriendCardModel.kt
  app/src/main/java/org/android/bbangzip/presentation/type/FriendMenuType.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/friend/FriendContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/friend/FriendRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/friend/FriendScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/friend/FriendViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/friend/navigation/FriendNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/pendingtodoadd/TodoAddPendingViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/todoadd/TodoAddViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ✨FEAT✨, 🐯승범🐯

#64 [feat] add study와 split study UI 구현
  app/src/main/java/org/android/bbangzip/presentation/component/bottomsheet/BbangZipDatePickerBottomSheet.kt
  app/src/main/java/org/android/bbangzip/presentation/component/bottomsheet/BbangZipListPickerBottomSheet.kt
  app/src/main/java/org/android/bbangzip/presentation/component/textfield/BbangZipBasicTextField.kt
  app/src/main/java/org/android/bbangzip/presentation/component/textfield/BbangZipSimpleTextField.kt
  app/src/main/java/org/android/bbangzip/presentation/component/topbar/BbangZipMenuTopBar.kt
  app/src/main/java/org/android/bbangzip/presentation/component/wheelpicker/BbangZipDatePicker.kt
  app/src/main/java/org/android/bbangzip/presentation/model/AddStudyData.kt
  app/src/main/java/org/android/bbangzip/presentation/model/SplitStudyData.kt
  app/src/main/java/org/android/bbangzip/presentation/type/AddStudyViewType.kt
  app/src/main/java/org/android/bbangzip/presentation/type/ShortTextFieldType.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/splitstudy/SplitStudyContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/splitstudy/SplitStudyNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/splitstudy/SplitStudyRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/splitstudy/SplitStudyScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/splitstudy/SplitStudyViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/util/base/BaseViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/util/casting/CastFunction.kt
  app/src/main/java/org/android/bbangzip/presentation/util/date/DateFunction.kt
  app/src/main/res/values/strings.xml
Labels: ✨FEAT✨, 🦁재민🦁

#41 [feat] subject screen ui구현
  app/src/main/java/org/android/bbangzip/presentation/component/button/BbangZipButton.kt
  app/src/main/java/org/android/bbangzip/presentation/component/card/AddSubjectCard.kt
  app/src/main/java/org/android/bbangzip/presentation/component/card/SubjectCard.kt
  app/src/main/java/org/android/bbangzip/presentation/model/card/SubjectCardModel.kt
  app/src/main/java/org/android/bbangzip/presentation/type/CardViewType.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/util/graphic/GraphicExt.kt
  app/src/main/res/values/strings.xml
Labels: ✨FEAT✨, 🦁재민🦁

#69 [feat] Exam API 연동
  app/src/main/java/org/android/bbangzip/data/datasource/remote/ExamRemoteDataSource.kt
  app/src/main/java/org/android/bbangzip/data/datasource/remote/SubjectRemoteDataSource.kt
  app/src/main/java/org/android/bbangzip/data/dto/response/ResponseExamNameDto.kt
  app/src/main/java/org/android/bbangzip/data/dto/response/ResponseSubjectFilterDto.kt
  app/src/main/java/org/android/bbangzip/data/repositoryImpl/remote/ExamRepositoryImpl.kt
  app/src/main/java/org/android/bbangzip/data/repositoryImpl/remote/SubjectRepositoryImpl.kt
  app/src/main/java/org/android/bbangzip/data/service/ExamService.kt
  app/src/main/java/org/android/bbangzip/data/service/SubjectService.kt
  app/src/main/java/org/android/bbangzip/di/RepositoryModule.kt
  app/src/main/java/org/android/bbangzip/di/ServiceModule.kt
  app/src/main/java/org/android/bbangzip/di/UseCaseModule.kt
  app/src/main/java/org/android/bbangzip/domain/model/SubjectDetailInfoEntity.kt
  app/src/main/java/org/android/bbangzip/domain/model/SubjectInfoEntity.kt
  app/src/main/java/org/android/bbangzip/domain/repository/remote/ExamRepository.kt
  app/src/main/java/org/android/bbangzip/domain/repository/remote/SubjectRepository.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/GetSubjectDetailUseCase.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/GetSubjectInfoUseCase.kt
  app/src/main/java/org/android/bbangzip/presentation/model/SubjectDetailInfo.kt
  app/src/main/java/org/android/bbangzip/presentation/model/SubjectInfo.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/mybadgecategory/MyBadgeCategoryContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/mybadgecategory/MyBadgeCategoryScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/mybadgecategory/MyBadgeCategoryViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetatilScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoViewModel.kt
Labels: ✨FEAT✨, 🐯승범🐯

#68 [refactor] Splash에서 자동 로그인 분기 처리
  app/src/main/java/org/android/bbangzip/presentation/ui/login/LoginRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/bbangzipdetail/BbangZipDetailScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainActivity.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/splash/SplashContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/splash/SplashRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/splash/SplashScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/splash/SplashViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/splash/navigation/SplashNavigation.kt
  app/src/main/java/org/android/bbangzip/ui/theme/Color.kt
  app/src/main/java/org/android/bbangzip/ui/theme/ColorScheme.kt
  app/src/main/res/drawable-xhdpi/img_bbangzip_logo.png
  app/src/main/res/drawable-xxhdpi/img_bbangzip_logo.png
  app/src/main/res/drawable/ic_bbangzip_circle_t_12.xml
  app/src/main/res/drawable/ic_bbangzip_logo_name.xml
  app/src/main/res/drawable/img_bbangzip_logo.png
Labels: ✅REFACTOR✅, 🐬지은🐬

#71 [feat] 과목명 수정, 과목 추가, 각오 메세지 등록 UI 구현
  app/src/main/java/org/android/bbangzip/presentation/component/card/SubjectCard.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addsubject/AddSubjectContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addsubject/AddSubjectNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addsubject/AddSubjectRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addsubject/AddSubjectScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addsubject/AddSubjectViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/motivationmessage/ModifyMotivationMessageContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/motivationmessage/ModifyMotivationMessageNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/motivationmessage/ModifyMotivationMessageRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/motivationmessage/ModifyMotivationMessageScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/motivationmessage/ModifyMotivationMessageViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/subjectname/ModifySubjectNameContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/subjectname/ModifySubjectNameNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/subjectname/ModifySubjectNameRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/subjectname/ModifySubjectNameScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/subjectname/ModifySubjectNameViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetatilScreen.kt
  app/src/main/res/values/strings.xml
Labels: ✨FEAT✨, 🦁재민🦁

#73 [feat] UI Graphic 적용
  app/src/main/java/org/android/bbangzip/presentation/component/card/FriendCard.kt
  app/src/main/java/org/android/bbangzip/presentation/model/card/FriendCardModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/friend/FriendContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/friend/FriendScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/mybadgecategory/MyBadgeCategoryScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/onboardingend/OnboardingEndScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/onboardingstart/OnboardingStartScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetatilScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoScreen.kt
  app/src/main/res/drawable/img_empty_view.xml
  app/src/main/res/drawable/img_friend_profile_1.xml
  app/src/main/res/drawable/img_friend_profile_2.xml
  app/src/main/res/drawable/img_friend_profile_3.xml
  app/src/main/res/drawable/img_friend_profile_4.xml
  app/src/main/res/drawable/img_mypage_header.xml
  app/src/main/res/drawable/img_no_peding_study.xml
  app/src/main/res/drawable/img_onboarding_end.xml
  app/src/main/res/drawable/img_onboarding_start.png
  app/src/main/res/drawable/img_onboarding_start.xml
  app/src/main/res/drawable/img_pending_study_zero.xml
  app/src/main/res/drawable/img_subject_detail_header.xml
  app/src/main/res/drawable/img_subject_header.xml
Labels: ✨FEAT✨, 🐯승범🐯

#75 [feat] SubjectService API 연동
  app/src/main/java/org/android/bbangzip/data/datasource/remote/SubjectRemoteDataSource.kt
  app/src/main/java/org/android/bbangzip/data/dto/request/RequestAddSubjectsDto.kt
  app/src/main/java/org/android/bbangzip/data/dto/request/RequestDeleteSubjectsDto.kt
  app/src/main/java/org/android/bbangzip/data/dto/request/RequestSubjectOptions.kt
  app/src/main/java/org/android/bbangzip/data/repositoryImpl/remote/SubjectRepositoryImpl.kt
  app/src/main/java/org/android/bbangzip/data/service/SubjectService.kt
  app/src/main/java/org/android/bbangzip/di/UseCaseModule.kt
  app/src/main/java/org/android/bbangzip/domain/repository/remote/SubjectRepository.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/DeleteSubjectsUseCase.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/PostAddSubjectNameUseCase.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/PutSubjectOptionsUseCase.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addsubject/AddSubjectViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/motivationmessage/ModifyMotivationMessageContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/motivationmessage/ModifyMotivationMessageNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/motivationmessage/ModifyMotivationMessageRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/motivationmessage/ModifyMotivationMessageViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/subjectname/ModifySubjectNameRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/modify/subjectname/ModifySubjectNameViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetatilScreen.kt
Labels: ✨FEAT✨, 🐯승범🐯

#77 [feat] subject detail에서 뻗는 navigation 구현
  app/src/main/java/org/android/bbangzip/presentation/model/AddStudyData.kt
  app/src/main/java/org/android/bbangzip/presentation/model/SplitStudyData.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/splitstudy/SplitStudyContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/splitstudy/SplitStudyRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/splitstudy/SplitStudyScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/splitstudy/SplitStudyViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetatilScreen.kt
Labels: ✨FEAT✨, 🦁재민🦁

#79 [feat] 전체적인 네비게이션 연결 및 온보딩/앱 아이콘 그래픽 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/android/bbangzip/data/dto/response/ResponseExamNameDto.kt
  app/src/main/java/org/android/bbangzip/data/repositoryImpl/local/UserLocalRepositoryImpl.kt
  app/src/main/java/org/android/bbangzip/domain/model/BadgeCardListEntity.kt
  app/src/main/java/org/android/bbangzip/domain/repository/local/UserLocalRepository.kt
  app/src/main/java/org/android/bbangzip/presentation/component/bottomsheet/BbangZipGetBadgeBottomSheet.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/login/LoginContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/login/LoginNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/bbangzipdetail/navigation/BbangZipDetailNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/mybadgecategory/navigation/MyBadgeCategoryNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/OnboardingContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/navigation/OnboardingEndNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/onboarding/OnboardingRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/onboarding/OnboardingScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/onboardingend/OnboardingEndRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/onboardingend/OnboardingEndScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/onboardingstart/OnboardingStartRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/onboardingstart/OnboardingStartScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/splash/SplashViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetatilScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoViewModel.kt
  app/src/main/proto/user_prefs.proto
  app/src/main/res/drawable-xhdpi/img_app_icon.png
  app/src/main/res/drawable-xxhdpi/img_app_icon.png
  app/src/main/res/drawable/img_app_icon.png
  app/src/main/res/drawable/img_onboarding_first.xml
  app/src/main/res/drawable/img_onboarding_second.xml
Labels: ✨FEAT✨, 🐬지은🐬

#78 [feat] 공부 조각 추가 api 연동
  app/src/main/java/org/android/bbangzip/data/datasource/remote/StudyRemoteDataSource.kt
  app/src/main/java/org/android/bbangzip/data/dto/request/RequestAddStudyDto.kt
  app/src/main/java/org/android/bbangzip/data/dto/response/ResponseGetBadgeDto.kt
  app/src/main/java/org/android/bbangzip/data/repositoryImpl/remote/StudyRepositoryImpl.kt
  app/src/main/java/org/android/bbangzip/data/service/StudyService.kt
  app/src/main/java/org/android/bbangzip/data/util/constant/ApiConstants.kt
  app/src/main/java/org/android/bbangzip/di/RepositoryModule.kt
  app/src/main/java/org/android/bbangzip/di/ServiceModule.kt
  app/src/main/java/org/android/bbangzip/di/UseCaseModule.kt
  app/src/main/java/org/android/bbangzip/domain/model/AddStudyEntity.kt
  app/src/main/java/org/android/bbangzip/domain/model/GetBadgeEntity.kt
  app/src/main/java/org/android/bbangzip/domain/model/PieceIdEntity.kt
  app/src/main/java/org/android/bbangzip/domain/repository/remote/StudyRepository.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/DeleteStudyPieceUseCase.kt
  app/src/main/java/org/android/bbangzip/domain/usecase/PostAddStudyUseCase.kt
  app/src/main/java/org/android/bbangzip/presentation/model/AddStudyData.kt
  app/src/main/java/org/android/bbangzip/presentation/model/SplitStudyData.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/addstudy/AddStudyViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/splitstudy/SplitStudyContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/splitstudy/SplitStudyRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/splitstudy/SplitStudyScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/splitstudy/SplitStudyViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetatilScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/util/casting/CastFunction.kt
  app/src/main/java/org/android/bbangzip/presentation/util/date/DateFunction.kt
Labels: ✨FEAT✨, 🐬지은🐬, 🦁재민🦁

#80 [feat] 1차 QA 반영
  app/src/main/java/org/android/bbangzip/presentation/component/balloon/BalloonContainer.kt
  app/src/main/java/org/android/bbangzip/presentation/component/card/SubjectCard.kt
  app/src/main/java/org/android/bbangzip/presentation/component/card/ToDoCard.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/MyScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/bbangzipdetail/BbangZipDetailScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/mybadgecategory/MyBadgeCategoryContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/mybadgecategory/MyBadgeCategoryScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/mybadgecategory/MyBadgeCategoryViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/onboarding/onboarding/OnboardingScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/SubjectViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailContract.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetailViewModel.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/subject/subjectdetail/SubjectDetatilScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoViewModel.kt
  app/src/main/res/drawable/img_subject_header.xml
  app/src/main/res/values/strings.xml
Labels: ✨FEAT✨, 🐯승범🐯
